source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'BlackboardMessenger' do
    pod 'Alamofire', '~> 4.4'
	pod 'SwiftWebSocket', '~> 2.6.5'
	pod 'ActionCableClient'
end
